schema_version = 3

[project]
uuid = "a92d1f88-9454-4742-8122-489edb35492b"
name = "buchwandler.github.io"

[ledgers.taskledger.mounts.data]
storage = "external"
root = "../ledger"

[ledgers.taskledger.mounts.runtime]
storage = "user-data"

[ledgers.taskledger.mounts.logs]
storage = "user-data"

[ledgers.taskledger.mounts.indexes]
storage = "cache"
